branches:
  except:
    - gh-pages
    - metarama 
language: C
complier:
  - gcc
before_install:
  - sudo apt-get install aspell-es
script: OUTPUT=`cat ortografia.md | aspell list -d es -p ./.aspell.es.pws`; if [ -n "$OUTPUT" ]; then echo $OUTPUT; exit 1; fi
